apache/sling-org-apache-sling-starter

- src/main/provisioning/sling-models-jacksonexporter.txt
Let me know if there is another place or component this should be updated in. However, after changing the file I confirmed in the Web Console that the 2.9.9 version of the jackson-annotations, jackson-core and jackson-databind components are in use.
> Update the jackson version to 2.9.9

- src/main/provisioning/composum.txt
I think, it's more clear to embed the settings of the only one config file in the composum-sling-core-config bundle into the provisioning script (that bundle was originally built for documentation and repair).
> embed Composum configuration bundle in the provisioning script

- src/main/features/app/slingshot.json
- src/main/features/base.json
- src/main/features/caconfig.json
- src/main/features/discovery.json
- src/main/features/event.json
- src/main/features/scripting.json
- src/main/features/validation.json
Switch all system users to pre-authentication, and also collapse/rename
some duplicated service user definitions.
> SLING-9786 - Use pre-authentication for system users

- src/main/features/boot.json
Update Starter with version org.apache.sling.settings:1.4.2 to resolve errors described in SLING-9648
> Re: SLING-9648 

- pom.xml
- src/main/features/base.json
- src/main/features/boot.json
the following dependencies were outdated:
```
[INFO]   org.apache.sling:org.apache.sling.auth.core ........... 1.5.0 -> 1.5.2
[INFO]   org.apache.sling:org.apache.sling.engine .............. 2.7.2 -> 2.7.4
[INFO]   org.apache.sling:org.apache.sling.repoinit.parser ..... 1.6.6 -> 1.6.8
[INFO]   org.apache.sling:org.apache.sling.resourceresolver .... 1.7.2 -> 1.7.4
[INFO]   org.apache.sling:org.apache.sling.xss ................ 2.2.8 -> 2.2.12
[INFO]   com.composum.nodes:composum-nodes-commons ............. 2.3.0 -> 2.6.1
[INFO]   com.composum.nodes:composum-nodes-console ............. 2.3.0 -> 2.6.1
[INFO]   com.composum.nodes:composum-nodes-jslibs .............. 2.3.0 -> 2.6.1
[INFO]   com.composum.nodes:composum-nodes-pckgmgr ............. 2.3.0 -> 2.6.1
[INFO] …
```
> update of various outdated org.apache.sling dependencies

- src/main/features/base.json
This enables installation of packages containing hooks via the OSGi
Installer Factory
> SLING-10362 allow hook execution for service user

- src/main/features/base.json
- src/main/features/scripting.json
Update the sling starter to use the latest bundles changed by SLING-9999
Specifically updates to these:
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   org.apache.sling:org.apache.sling.scripting.core ...... 2.3.4 -> 2.3.6
[INFO]   org.apache.sling:org.apache.sling.scripting.jsp ....... 2.5.0 -> 2.5.2
[INFO]   org.apache.sling:org.apache.sling.scripting.sightly ...
[INFO]                                               1.4.6-1.4.0 -> 1.4.8-1.4.0
[INFO]   org.apache.sling:org.apache.sling.servlets.resolver ...
[INFO]                                                         2.7.12 -> 2.7.14
And this new required bundle:
org.apache.sling:org.apache.sling.scripting.spi:1.0.2
> SLING-10400 Update bundles in sling starter

- src/main/features/oak/persistence/oak_persistence_mongods.json
This solves problems connecting to MongoDB after the mongo-java-driver was upgraded. As @rombert [says in SLING-10402](https://issues.apache.org/jira/browse/SLING-10402?focusedCommentId=17348150&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17348150) :
_According to https://jackrabbit.apache.org/oak/docs/nodestore/document/mongo-document-store.html the version of Oak we use (1.38.0) supports MongoDB 4.0.x . Also according to https://github.com/apache/jackrabbit-oak/blob/651f1b96634268ea7285231cc85f40eda46fa01e/oak-parent/pom.xml#L57 , the version of the MongoDB driver we should use is 3.8.2 ._
> SLING-10402 downgrade org.mongodb:mongo-java-driver to 3.8.2

- pom.xml
- src/main/features/oak/persistence/oak_persistence_mongods.json
- src/test/java/org/apache/sling/launchpad/SmokeIT.java
These changes cause two Sling instances to be started for testing, with tar and mongo configs.
Docker services are required to run the mongo test.
I wasn't able to get the dynamic mongo port setup to work ,see TODO in pom.xml, I don't have time to dig deeper right now, if someone wants to have a look feel free!
Note also that the mongo container might not be stopped upon some types of test failures.
> SLING-10402 - run SmokeIT on both tar and mongo features

- pom.xml
- src/main/features/oak/persistence/oak_persistence_mongods.json
- src/test/java/org/apache/sling/launchpad/SmokeIT.java
Also, update to org.mongodb:mongo-java-driver:3.12.8 which is now compatible with the oak release
> SLING-10459 Update starter to use Oak 1.40.0

- src/main/features/boot.json
> SLING-10832 - JaxbMarhshallingTest fails on Java 17

- pom.xml
Set a 60 seconds start timeout and make it configurable.
> SLING-11052 - Increase starter timeout during integration tests

- pom.xml
Revert the feature launcher update since it immediately errors out:
Error: Unable to initialize main class org.apache.sling.feature.launcher.impl.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
> SLING-11140 Update bundles to the latest releases

- src/main/features/base.json
Allow a thread pool named 'oak'.
> SLING-11193 - Configure the quartz scheduler with the known allowed thread pool names

- src/main/features/scripting.json
Opening http://localhost/htl/repl.html gives the following warning:
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.9.1
ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.9.1
This is caused by Sling HTL Engine being compiled with ANTLR 4.7.1. This is probably harmless (HTL works fine seemingly), but one static field was removed in antlr-runtime (no idea how important), so the versions are in principle not ABI compatible.
> Downgrade ANTLR to match Sling HTL Engine

- README.md
- src/main/features/boot.json
Currently blocked by https://issues.apache.org/jira/browse/SLING-11173
> SLING-11170 update to DS 1.5 compatible implementation of Felix SCR

- .sling-module.json
- README.md
- pom.xml
- src/main/features/test/junit.json
- src/main/features/test/test-content-repoinit.txt
- src/main/features/test/test-content.json
Execute the launchpad-testing test suite in the regular starter build.
> SLING-7935 - Move launchpad-testing module into the main starter repository

- src/main/features/event.json
In the starter event.json, the sling-event thread pool factory has an invalid configuration that results in an IllegalArgumentException getting thrown at runtime.  This causes all the scheduled jobs to not get triggered.
Specifically, the maxPoolSize is smaller than the minPoolSize
> SLING-11585 Invalid config for the sling-event thread pool factory

- pom.xml
Use random container names to prevent naming conflicts while running CI builds concurrently.
> SLING-11701 - Starter CI builds are sometimes failing with an error about a conflict with the docker container name

- pom.xml
This reverts commit 98a87a8edc2e9044fa730ebf93d792a0ac7aab49.
Version 0.43.2 has broken DockerHub pushes, see https://github.com/fabric8io/docker-maven-plugin/issues/1698
> Revert "chore(deps): update dependency io.fabric8:docker-maven-plugin to v0.43.2"

- pom.xml
With moving to Java 11 as a baseline, these classes are seens as conflicting with the ones provided by the JDK:
The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
> Exclude the xmlParserAPIs dependency from the classpath

- pom.xml
- src/main/features/maintenance.json
- src/main/features/oak/oak_base.json
bump oak-* to 1.56.0
bump jackrabbit-* to 2.20.12
bump o.a.sling.jcr.maintenance to 1.1.0
bump o.a.sling.jcr.oak.server to 1.4.0
> update apache jackrabbit, oak and related

- renovate.json
- src/main/features/oak/oak_base.json
Remove the bundle from the Starter and drop the no longer needed Renovate config. Oak now uses its own private copy of Guava.
> SLING-12101 - Remove Guava from the Starter

- src/main/features/app/starter.json
- src/main/features/healthcheck.json
The configuration 
`org.apache.felix.hc.core.impl.filter.ServiceUnavailableFilter~startupandshutdown` found in `src/main/features/healthcheck.json` references the starter content in its `responseTestFor503` property which will cause the model to fail to build if the starter content is not included in the aggregated feature model.
To keep the Starter Content-related features together, I suggest moving this configuration to `src/main/features/app/starter.json`
> SLING-12117 - Moving ServiceUnavailableFilter~startupandshutdown to app/starter feature

- src/main/features/app/composum.json
Currently returns a 404 due to the proxy not being configured.
> SLING-12154 - Add Generic Proxy configuration for Composum Health Checks

- src/main/features/boot.json
Remove org.apache.aries.spifly.auto.* framework properties that are no longer in use after commit 31e6d31.
> SLING-11836 : Add Jakarta JSON support to the Sling Starter

- src/main/features/test/test-content.json
depends on https://github.com/apache/sling-org-apache-sling-launchpad-integration-tests/pull/21
> SLING-12535 Remove fragment bundle test

- .sling-module.json
until we find the root cause of the test flakyness with windows
> SLING-12600 temporarily limit test runs to linux again

- pom.xml
- src/main/features/test/test-content.json
This way new tests and associated services will be picked up.
> chore: use version 14-SNAPSHOT for integration tests and test services

- src/main/features/base.json
Register the MBean Server using the new Aries bundle.
> SLING-12367 - MBean platform server not registered for Sling Starter

- pom.xml
- src/main/features/test/junit.json
- use junit.core compatible with Jakarta JSON
- stop importing Johnzon 1.0 for test JSON support; the latest launchpad testing module brings in Johnzon 2.0
> SLING-12732 - Migrate Starter tests to Jakarta JSON
